const express = require('express')
const app = express()
const port = 3001
const cors = require('cors')
const connection = require('./connection')
const area_routes = require('./routes/area_routes')
const user_routes = require('./routes/user_routes')
const computer_routes = require('./routes/computer_routes')
const maintenance_routes = require('./routes/maintenance_routes')

app.use(express.json())
app.use(cors())
app.use('/api/v1', area_routes)
app.use('/api/v1', user_routes)
app.use('/api/v1', computer_routes)
app.use('/api/v1', maintenance_routes)
app.get('/', (req, res) => res.send('Hola!'))
app.listen(port, "0.0.0.0",() => console.log(`Example app listening on port ${port} :)!`))